### ISSUE TITLE
When mouse up, content goes back to initial position

### ISSUE THREAD

**Issue by shqnks** [ilyashubin/scrollbooster#18]

**Comment by shqnks** [comment]
I used another plugin cause I couldn't make scrollbooster work as I wanted

**Comment by scriptype** [comment]
I was losing my mind over this, but I realized that I'm initializing ScrollBooster more than one time on the same `viewport` element.

This was due to re-rendering a component without re-creating its container (only refreshing inside), but the container was supposed to be the viewport of ScrollBooster. So it kept getting re-initialized over the same element.

Sharing this for the people of future.

**Comment by GalahadXVI** [comment]
Another possible reason for this issue (at least in my case):

If the content is loaded dynamically (e.g., when using Alpine.js), ScrollBooster may initialize before the element is fully rendered. This causes the scroll behavior to reset or snap bac.

I fixed it by applying ScrollBooster only after the element has been fully loaded in the DOM/


```js
const img = document.querySelector('#image');
img.addEventListener('load', () => {
    new ScrollBooster({
        viewport: document.querySelector('#viewport'),
        content: img,
    });
});
```

Or a lazy way is to just add a timeout.
```js
                setTimeout(function(){
                            new ScrollBooster({
                                viewport: document.getElementById('#viewport'),
                                 content: document.querySelector('#image'),
                            });
                }, 1000);
```
